# Change these first
owner: mvwicky # Your GitHub organization or username, where this repository lives
repo: holdmyuptime # The name of this repository
user-agent: mvwicky
sites:
  - name: Hold My Pics
    url: https://holdmypics.com/
    icon: https://holdmypics.com/favicon.ico
  - name: "Where Was I Going With That?"
    url: https://www.wherewasigoing.com/
    icon: https://www.wherewasigoing.com/blog/assets/img/icons/favicon.ico
  - name: Crunchy Arcane Riddles
    url: https://crunchy-arcane-riddles.com/
    icon: https://crunchy-arcane-riddles.com/favicon.ico
  

status-website:
  baseUrl: /holdmyuptime
  logoUrl: https://www.wherewasigoing.com/blog/assets/img/icons/favicon.ico
  favicon: https://www.wherewasigoing.com/blog/assets/img/icons/favicon.ico
  name: Hold My Uptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
